import { Fraunces } from "next/font/google";
import "./globals.scss";
import { NavBar } from "./components";

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fraunces.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
